services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: CHATBOT_MODE
        value: hybrid
      - key: CHATBOT_FALLBACK_ENABLED
        value: true
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo
      - key: OPENAI_MAX_TOKENS
        value: 500
      - key: OPENAI_TEMPERATURE
        value: 0.7
      - key: CHATBOT_MAX_CONTEXT_LENGTH
        value: 2000
      # Add your API keys in Render dashboard:
      # - key: OPENAI_API_KEY
      #   value: your_openai_api_key
      # - key: ANTHROPIC_API_KEY
      #   value: your_anthropic_api_key